#!/usr/bin/env python
"""Emit a joint-IV pair config from two Worlds meta entries.

Bridges the Worlds detection funnel to the joint-IV kit
(docs/joint_iv_reuse_plan.md): given two species_ids from
worlds/meta.toml (typically a pair off scripts/worlds_shortlist.py's
ranking), write pairs/<focal>__vs__<opp>.toml with the entries' exact
baked movesets and shadow flags, both bait modes, and the focal's dive
replay blob when one exists.

The moveset comes from the meta entry (modal-or-default, the same
moveset the Worlds Tier-1/2 planes simmed), which is what makes the
kit's Tier-2 cross-check (scripts/joint_iv_crosscheck.py) applicable.
Per-entry injected_move_ids carry through (Thievul's Icy Wind CD lag).

Usage:
    python scripts/joint_iv_from_worlds.py wigglytuff lickilicky
    python scripts/joint_iv_from_worlds.py quagsire_shadow lickilicky --force
"""
import argparse
import pathlib
import re
import sys
import tomllib

REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / 'scripts'))

META_TOML = REPO / 'worlds' / 'meta.toml'
PAIRS_DIR = REPO / 'pairs'
REPLAY_DIR = REPO / 'userdata' / 'replay'


def load_entries():
    with open(META_TOML, 'rb') as f:
        meta = tomllib.load(f)
    return {e['species_id']: e for e in meta['entries']}


def move_short(move_id):
    """Charged-move label shorthand: THE move_abbr rule, lowercased
    (SHADOW_SNEAK -> ss, SWIFT -> swi). Labels are permanent baked
    identifiers; two early pairs (iwsw/acpa) predate the move_abbr
    routing and keep their committed labels."""
    from deep_dive_analysis import move_abbr
    return move_abbr(move_id).lower()


def grid_label(charged_ids, bait):
    return (''.join(move_short(c) for c in charged_ids)
            + ('_bait' if bait else '_nobait'))


def find_replay_blob(entry, league='great'):
    """Newest dive replay blob for the focal species (+shadow), if any.
    The dive stamps species with underscores for spaces/forms
    (e.g. Corsola_Galarian); shadow dives carry a _shadow suffix."""
    species_part = re.sub(r'[^A-Za-z0-9]+', '_', entry['species']).strip('_')
    suffix = f'_{league}_shadow' if entry['shadow'] else f'_{league}'
    pat = f'*_{species_part}{suffix}.replay.pkl.gz'
    hits = sorted(REPLAY_DIR.glob(pat))
    return hits[-1] if hits else None


def gamemaster_species_name(entry):
    """The plain speciesName the sim layer resolves (shadow is a flag,
    not a name, in the kit; the moveset fork arms share one species)."""
    return entry['species']


def emit(focal_id, opp_id, force=False):
    entries = load_entries()
    for sid in (focal_id, opp_id):
        if sid not in entries:
            sys.exit(f'ABORT: {sid} not in worlds/meta.toml '
                     f'(known: {sorted(entries)[:8]}...)')
    f, o = entries[focal_id], entries[opp_id]

    out = PAIRS_DIR / f'{focal_id}__vs__{opp_id}.toml'
    if out.exists() and not force:
        sys.exit(f'ABORT: {out} exists (--force to overwrite)')

    injected = list(f.get('injected_move_ids', []))
    blob = find_replay_blob(f)
    charged = list(f['charged_move_ids'])
    lines = [
        f'# {f["name"]} vs {o["name"]} -- generated by '
        'scripts/joint_iv_from_worlds.py',
        f'# from worlds/meta.toml (movesets = the Worlds-baked movesets, '
        'so the',
        '# Tier-2 cross-check applies). Edit freely; the generator never '
        'overwrites',
        '# without --force.',
        '',
        '[pair]',
        'league = "great"',
        f'focal = "{gamemaster_species_name(f)}"',
        f'focal_shadow = {str(bool(f["shadow"])).lower()}',
        f'focal_slug = "{focal_id}"',
        f'opponent = "{gamemaster_species_name(o)}"',
        f'opponent_shadow = {str(bool(o["shadow"])).lower()}',
        f'opponent_slug = "{opp_id}"',
        f'opponent_fast = "{o["fast_move_id"]}"',
        ('opponent_charged = ['
         + ', '.join(f'"{c}"' for c in o['charged_move_ids']) + ']'),
        f'data_dir = "userdata/joint_iv/{focal_id}__vs__{opp_id}"',
        ('injected_moves = ['
         + ', '.join(f'"{m}"' for m in injected) + ']'),
    ]
    if blob is not None:
        lines.append(f'replay_blob = "{blob.relative_to(REPO)}"')
    else:
        lines.append('# replay_blob: none found for this focal '
                     '(meta panels render honest-absent)')
    if o.get('injected_move_ids'):
        lines.append('opponent_injected_moves = ['
                     + ', '.join(f'"{m}"' for m in o['injected_move_ids'])
                     + ']')
    lines += [
        '',
        '# FROZEN SLOT KEYS -- the page JS locates the breakpoints layer by',
        '# these historical spellings (thievul=focal slot, lickitung=opp',
        '# slot, licki=opp shorthand); they are slot names, not species.',
        '# The page builder hard-aborts when breakpoints.json lacks them.',
        '[breakpoints]',
        'focal_key = "thievul"',
        'opp_key = "lickitung"',
        'opp_short = "licki"',
    ]
    if o.get('default_disagrees'):
        lines += [
            '# The OPPONENT worlds modal moveset deliberately differs from',
            '# PvPoke\'s rankings default (see the focal note above for the',
            '# same rule).',
            'assert_opponent_default_moveset = false',
        ]
    if f.get('default_disagrees'):
        lines += [
            '# The Worlds MODAL moveset (what the field actually runs, '
            f"{f.get('moveset_modal_pct', '?')}% of n={f.get('moveset_n', '?')})",
            '# deliberately differs from PvPoke\'s rankings default -- an',
            '# explicit opt-out of the default-moveset check, never a',
            '# silently absent one.',
            'assert_focal_default_moveset = false',
        ]
    for bait in (True, False):
        lines += [
            '',
            '[[grids]]',
            f'label = "{grid_label(charged, bait)}"',
            f'focal_fast = "{f["fast_move_id"]}"',
            ('focal_charged = ['
             + ', '.join(f'"{c}"' for c in charged) + ']'),
            f'bait = {str(bait).lower()}',
        ]
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text('\n'.join(lines) + '\n')
    print(f'wrote {out}')
    if blob is None:
        print(f'  NOTE: no replay blob found for {f["name"]}')

    from joint_iv_config import load_pair, preflight_moveset_legality
    cfg = load_pair(out)
    preflight_moveset_legality(cfg)
    print('  config loads + moveset legality preflight OK')
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument('focal', help='worlds/meta.toml species_id (focal)')
    ap.add_argument('opponent', help='worlds/meta.toml species_id (opponent)')
    ap.add_argument('--force', action='store_true')
    args = ap.parse_args()
    emit(args.focal, args.opponent, force=args.force)


if __name__ == '__main__':
    main()
