#!/usr/bin/env bash
# Publish userdata/website/ to pogodives.com (the primary home; the old
# mglerner.com/pogo-dives path 301-redirects here via a hand-placed .htaccess).
#
# Flow on every run:
#   1. Regenerate userdata/website/index.html from per-dive meta.toml files
#      (so a fresh dive dropped in userdata/website/<slug>/ with a meta.toml
#      is picked up without a separate step).
#   2. Run link verification (scripts/verify_article_links.py --ship)
#      and em/en-dash verification (scripts/verify_no_unicode_dashes.py
#      --ship). Any broken internal link or unicode-dash hit aborts the
#      publish before anything hits the server. Pass --skip-verify to
#      bypass (e.g. publishing an in-progress page where you know a
#      link will dangle temporarily).
#   3. rsync to mglerner.com:/home/mglerner/pogodives.com/ with --delete
#      --delete-excluded, so anything removed locally -- or matching an
#      exclude pattern -- is also removed on the server.
#
# Excluded from the publish: meta.toml (site-index build metadata, not
# user-facing). Server-side copies are removed on next push via
# --delete-excluded.
#
# Default is dry-run. Pass --push to actually send the files.
#
# Usage:
#     scripts/publish_website.sh                  # dry run (safe default)
#     scripts/publish_website.sh --push           # actually push
#     scripts/publish_website.sh --push --skip-verify  # bypass link check

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="${REPO_ROOT}/userdata/website/"
DEST="mglerner.com:/home/mglerner/pogodives.com/"

PUSH=false
SKIP_VERIFY=false
PARTIAL=false
for arg in "$@"; do
  case "$arg" in
    --push) PUSH=true ;;
    --skip-verify) SKIP_VERIFY=true ;;
    --partial) PARTIAL=true ;;
    *) echo "error: unknown arg '$arg'" >&2; exit 2 ;;
  esac
done

if [ ! -d "$SRC" ]; then
  echo "error: $SRC does not exist" >&2
  exit 1
fi

# --partial: publish a bake that is still running.
#
# It does ONE thing: relax the gates that assume a complete corpus. It does not
# pull anything down, rewrite anything, or make per-page decisions -- so what
# it publishes is exactly the local tree, same as a normal publish.
#
# rsync still runs with --delete, so live content absent from $SRC is removed.
# That is intended: everything the bake regenerates (dive pages, the 61 ML IV
# guides, comparisons/, the Reader's Guides) comes back when the chain reaches
# its step, and stale pre-rebalance pages should not linger meanwhile.
#
# Content NOT regenerated by any chain step is a one-off decision, not this
# script's job. As of 2026-09-11 that is the *robustness.html joint-IV pages
# (archived to userdata/_preserved/robustness_pages_2026-09-11/ and
# deliberately retired -- build_joint_iv_page.py is run by hand when wanted)
# and the Cramorant strategy article (rebuild with
# render_pogodives_strategy_article.py once BOTH cramorant dives exist; it
# reads the GL and UL dive pages).
# Completeness gate (added 2026-09-10). rsync runs with --delete, so this
# script MIRRORS: whatever is in $SRC becomes the entire live site, and
# anything missing locally is deleted from the server. That was safe while
# userdata/website was always fully populated. It is not safe now -- the
# 2026-09-09 userdata wipe means a publish part-way through a bake would
# delete every page the bake had not reached yet.
#
# The existing "-d $SRC" check only catches the empty case. This catches the
# PARTIAL case: refuse when the site has materially fewer dive pages than the
# dive list says it should.
EXPECTED_DIVES=$(cd "$REPO_ROOT" && python -c "
import sys; sys.path.insert(0, 'scripts')
from dive_registry import all_dives
print(len(all_dives()))
" 2>/dev/null || echo 0)
ACTUAL_DIVES=$(find "$SRC" -mindepth 2 -maxdepth 2 -name index.html 2>/dev/null | wc -l | tr -d ' ')
if [ "$SKIP_VERIFY" = false ] && [ "$EXPECTED_DIVES" -gt 0 ]; then
  MIN_DIVES=$(( EXPECTED_DIVES * 9 / 10 ))
  if [ "$PARTIAL" = true ]; then
    echo "note: --partial, skipping the completeness gate"
    echo "      dive pages: $ACTUAL_DIVES of ~$EXPECTED_DIVES"
  elif [ "$ACTUAL_DIVES" -lt "$MIN_DIVES" ]; then
    echo "error: refusing to publish an INCOMPLETE site." >&2
    echo "  dive pages found: $ACTUAL_DIVES; expected ~$EXPECTED_DIVES (floor $MIN_DIVES)" >&2
    echo "  rsync runs with --delete, so publishing now would REMOVE the" >&2
    echo "  missing pages from pogodives.com." >&2
    echo "  fix:    finish the bake (scripts/run_website_dives.py)" >&2
    echo "  bypass: --partial (safe, pulls live content down first)" >&2
    echo "          --skip-verify (UNSAFE mid-bake: mirrors as-is)" >&2
    exit 1
  fi
fi

# Card-rerender gate: a renderer-side fix landed after the dives were simmed,
# so the shipped HTML is stale until rebuilt from the replay blobs. The
# sentinel is dropped when that happens and cleared by rerender_dive_cards.py.
# (Bypass with --skip-verify, same as the link/dash checks.)
SENTINEL="${REPO_ROOT}/userdata/.cards_rerender_pending"
if [ "$SKIP_VERIFY" = false ] && [ -f "$SENTINEL" ]; then
  echo "error: dive cards need re-rendering before publish." >&2
  echo "  reason: $(head -1 "$SENTINEL" 2>/dev/null)" >&2
  echo "  fix:    python scripts/rerender_dive_cards.py   (replays the blobs, clears this gate)" >&2
  echo "  bypass: re-run with --skip-verify" >&2
  exit 1
fi

# The guides interpolate live numbers from the dive corpus (opponent_count,
# iv_space_size, envelope_* counts, ...), so a part-way corpus makes
# build_guides.py hard-fail on unresolved tokens. Under --partial that failure
# is EXPECTED, not a defect: skip the rebuild and keep the guides already on
# the server (the push below leaves them untouched because they still exist in
# $SRC). They are regenerated for real by the chain's "Building Reader's
# Guides" step once the corpus is complete.
if [ "$PARTIAL" = true ]; then
  echo "Skipping reader-guide rebuild (--partial: dive corpus is incomplete,"
  echo "  build_guides.py would fail on unresolved tokens). Live guides kept."
else
  echo "Regenerating reader guides..."
  python "${REPO_ROOT}/scripts/build_guides.py"
fi
echo

# Worlds 2026 re-render is OPT-IN as of 2026-08-31. The shipped pages are
# frozen at a Worlds-era engine/gamemaster; re-rendering them from main would
# restamp them against current data without re-simming, i.e. publish pages that
# claim a vintage they were not baked at. Set WORLDS_RERENDER=1 to force it
# (only meaningful with the gamemaster re-pinned per TODO.md). The surfaces
# retire at the Twilight Trails site update -- see scripts/run_ship_gates.py.
if [ "${WORLDS_RERENDER:-0}" = "1" ] && [ -f "${REPO_ROOT}/worlds/planes/manifest.json" ]; then
  echo "Regenerating Worlds 2026 pages (WORLDS_RERENDER=1)..."
  if [ -f "${REPO_ROOT}/worlds/planes/tier2/manifest.json" ]; then
    python "${REPO_ROOT}/scripts/build_worlds_pair_pages.py"
  fi
  python "${REPO_ROOT}/scripts/build_worlds_cmp.py"
  python "${REPO_ROOT}/scripts/build_worlds_explorer.py"
  python "${REPO_ROOT}/scripts/build_worlds_pages.py"
  echo
fi

echo "Regenerating index.html..."
python "${REPO_ROOT}/scripts/build_website_index.py"
echo

# Ship gates assume a COMPLETE corpus (e.g. test_article_slug_wiring checks the
# Cramorant dive links its strategy article -- an article a partial bake has
# not rebuilt yet). Under --partial those failures are expected, so skip the
# gates but say so loudly rather than silently lowering the bar.
if [ "$PARTIAL" = true ] && [ "$SKIP_VERIFY" = false ]; then
  echo "Skipping ship gates (--partial: they assume a complete corpus)."
  echo "  Known-failing on a partial bake: test_article_slug_wiring"
  echo "  (Cramorant dive -> strategy article link; the article is rebuilt"
  echo "  after the bake). Re-run gates on the full publish."
  echo
elif [ "$SKIP_VERIFY" = true ]; then
  echo "Skipping ship gates (--skip-verify)."
else
  echo "Running ship gates (roster: scripts/run_ship_gates.py)..."
  if ! python "${REPO_ROOT}/scripts/run_ship_gates.py"; then
    echo
    echo "error: a ship gate failed -- fix the violations or re-run with --skip-verify" >&2
    exit 1
  fi
  echo
fi

RSYNC_EXCLUDES=(--exclude='meta.toml')

if [ "$PUSH" = true ]; then
  echo "Pushing ${SRC} -> ${DEST}"
  rsync -avzh --delete --delete-excluded "${RSYNC_EXCLUDES[@]}" "$SRC" "$DEST"
  echo
  echo "Done. Site should be live at https://pogodives.com/"
else
  echo "Dry run (pass --push to actually push)"
  echo "Source: ${SRC}"
  echo "Dest:   ${DEST}"
  echo
  rsync -avzhn --delete --delete-excluded "${RSYNC_EXCLUDES[@]}" "$SRC" "$DEST"
  echo
  echo "(dry run - nothing was actually sent; pass --push to publish)"
fi
